version: "3.9"
services:
  students-db:
    image: 'mysql:latest'
    container_name: students_db_container
    environment:
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_DATABASE=students_db'
      - 'MYSQL_USER=darkus'
      - 'MYSQL_PASSWORD=1999'
    ports:
      - "3307:3306"
    networks:
      - microservices_databases_network
    volumes:
      - students_db_volume:/var/lib/mysql

  courses-db:
    image: 'mysql:latest'
    container_name: courses_db_container
    environment:
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_DATABASE=courses_db'
      - 'MYSQL_USER=darkus'
      - 'MYSQL_PASSWORD=1999'
    ports:
      - "3308:3306"
    networks:
      - microservices_databases_network
    volumes:
      - courses_db_volume:/var/lib/mysql

networks:
  microservices_databases_network:
volumes:
  students_db_volume:
  courses_db_volume:
