version: "3.9"
services:
  students-db:
    image: 'mysql:latest'
    container_name: students_db_container
    environment:
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_DATABASE=students_db'
      - 'MYSQL_USER=darkus'
      - 'MYSQL_PASSWORD=1999'
    ports:
      - "3307:3306"
    networks:
      - microservices_databases_network
    volumes:
      - students_db_volume:/var/lib/mysql

  courses-db:
    image: 'mysql:latest'
    container_name: courses_db_container
    environment:
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_DATABASE=courses_db'
      - 'MYSQL_USER=darkus'
      - 'MYSQL_PASSWORD=1999'
    ports:
      - "3308:3306"
    networks:
      - microservices_databases_network
    volumes:
      - courses_db_volume:/var/lib/mysql

  auth-db:
    image: 'postgres'
    container_name: auth_db_container
    environment:
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_DB=auth_db'
      - 'POSTGRES_USER=user'
    ports:
      - "5432:5432"
    networks:
      - microservices_databases_network
    volumes:
      - auth_db_postgres_volume:/var/lib/postgresql/data


networks:
  microservices_databases_network:
volumes:
  students_db_volume:
  courses_db_volume:
  auth_db_postgres_volume:
