eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: students
          uri: http://localhost:9090
          predicates:
            - Path=/api/student/**
          filters:
            - AuthenticationFilter


        - id: courses
          uri: http://localhost:9080
          predicates:
            - Path=/api/course/**
          filters:
            - AuthenticationFilter


        - id: auth
          uri: http://localhost:9999
          predicates:
            - Path=/api/auth/**